# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WatchForWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from WatchForWindow_UI_Functions import guiFunctions

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class WFWMainDialog(object):
    def setupUi(self, MainDialog):
        self.MW = MainDialog
        self.timer = None
        MainDialog.setObjectName(_fromUtf8("MainDialog"))
        MainDialog.resize(390, 390)
        MainDialog.setMinimumSize(QtCore.QSize(450, 390))
        MainDialog.setMaximumSize(QtCore.QSize(900, 600))
        self.mainDialogLayout = QtGui.QGridLayout(MainDialog)
        self.mainDialogLayout.setObjectName(_fromUtf8("mainDialogLayout"))
        self.curentStatusLabel = QtGui.QLabel(MainDialog)
        self.curentStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.curentStatusLabel.setObjectName(_fromUtf8("curentStatusLabel"))
        self.mainDialogLayout.addWidget(self.curentStatusLabel, 1, 0, 1, 1)
        self.StartButton = QtGui.QPushButton(MainDialog)
        self.StartButton.setMaximumSize(QtCore.QSize(87, 16777215))
        self.StartButton.setObjectName(_fromUtf8("StartButton"))
        self.mainDialogLayout.addWidget(self.StartButton, 1, 1, 1, 1)
        self.QuitButton = QtGui.QPushButton(MainDialog)
        self.QuitButton.setMaximumSize(QtCore.QSize(87, 16777215))
        self.QuitButton.setObjectName(_fromUtf8("QuitButton"))
        self.mainDialogLayout.addWidget(self.QuitButton, 1, 2, 1, 1)
        self.StopButton = QtGui.QPushButton(MainDialog)
        self.StopButton.setMinimumSize(QtCore.QSize(51, 0))
        self.StopButton.setMaximumSize(QtCore.QSize(51, 16777215))
        self.StopButton.setObjectName(_fromUtf8("StopButton"))
        self.mainDialogLayout.addWidget(self.StopButton, 1, 3, 1, 1)
        self.mainFrame = QtGui.QFrame(MainDialog)
        self.mainFrame.setLineWidth(0)
        self.mainFrame.setObjectName(_fromUtf8("mainFrame"))
        self.mainGroupBoxLayout = QtGui.QGridLayout(self.mainFrame)
        self.mainGroupBoxLayout.setMargin(0)
        self.mainGroupBoxLayout.setHorizontalSpacing(0)
        self.mainGroupBoxLayout.setVerticalSpacing(2)
        self.mainGroupBoxLayout.setObjectName(_fromUtf8("mainGroupBoxLayout"))
        self.windowOptionsGroup = QtGui.QGroupBox(self.mainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windowOptionsGroup.sizePolicy().hasHeightForWidth())
        self.windowOptionsGroup.setSizePolicy(sizePolicy)
        self.windowOptionsGroup.setObjectName(_fromUtf8("windowOptionsGroup"))
        self.gridLayout = QtGui.QGridLayout(self.windowOptionsGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.windowName = QtGui.QLineEdit(self.windowOptionsGroup)
        self.windowName.setObjectName(_fromUtf8("windowName"))
        self.gridLayout.addWidget(self.windowName, 0, 1, 1, 1)
        self.windowNameLabel = QtGui.QLabel(self.windowOptionsGroup)
        self.windowNameLabel.setObjectName(_fromUtf8("windowNameLabel"))
        self.gridLayout.addWidget(self.windowNameLabel, 0, 0, 1, 1)
        self.mainGroupBoxLayout.addWidget(self.windowOptionsGroup, 0, 0, 1, 1)
        self.emailMessageGroup = QtGui.QGroupBox(self.mainFrame)
        self.emailMessageGroup.setObjectName(_fromUtf8("emailMessageGroup"))
        self.gridLayout_3 = QtGui.QGridLayout(self.emailMessageGroup)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.emailFromLabel = QtGui.QLabel(self.emailMessageGroup)
        self.emailFromLabel.setObjectName(_fromUtf8("emailFromLabel"))
        self.gridLayout_3.addWidget(self.emailFromLabel, 0, 0, 1, 1)
        self.emailFromTextbox = QtGui.QLineEdit(self.emailMessageGroup)
        self.emailFromTextbox.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.emailFromTextbox.setObjectName(_fromUtf8("emailFromTextbox"))
        self.gridLayout_3.addWidget(self.emailFromTextbox, 0, 1, 1, 1)
        self.emailToLabel = QtGui.QLabel(self.emailMessageGroup)
        self.emailToLabel.setObjectName(_fromUtf8("emailToLabel"))
        self.gridLayout_3.addWidget(self.emailToLabel, 0, 2, 1, 1)
        self.emailToTextbox = QtGui.QLineEdit(self.emailMessageGroup)
        self.emailToTextbox.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.emailToTextbox.setObjectName(_fromUtf8("emailToTextbox"))
        self.gridLayout_3.addWidget(self.emailToTextbox, 0, 3, 1, 1)
        self.emailSubjectLabel = QtGui.QLabel(self.emailMessageGroup)
        self.emailSubjectLabel.setObjectName(_fromUtf8("emailSubjectLabel"))
        self.gridLayout_3.addWidget(self.emailSubjectLabel, 1, 0, 1, 1)
        self.emailSubjectTextbox = QtGui.QLineEdit(self.emailMessageGroup)
        self.emailSubjectTextbox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.emailSubjectTextbox.setFrame(True)
        self.emailSubjectTextbox.setDragEnabled(False)
        self.emailSubjectTextbox.setObjectName(_fromUtf8("emailSubjectTextbox"))
        self.gridLayout_3.addWidget(self.emailSubjectTextbox, 1, 1, 1, 3)
        self.emailMessageLabel = QtGui.QLabel(self.emailMessageGroup)
        self.emailMessageLabel.setObjectName(_fromUtf8("emailMessageLabel"))
        self.gridLayout_3.addWidget(self.emailMessageLabel, 2, 0, 1, 1)
        self.emailMessageTextbox = QtGui.QLineEdit(self.emailMessageGroup)
        self.emailMessageTextbox.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.emailMessageTextbox.setObjectName(_fromUtf8("emailMessageTextbox"))
        self.gridLayout_3.addWidget(self.emailMessageTextbox, 2, 1, 1, 3)
        self.mainGroupBoxLayout.addWidget(self.emailMessageGroup, 2, 0, 1, 1)
        self.generalEmailSettings = QtGui.QGroupBox(self.mainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generalEmailSettings.sizePolicy().hasHeightForWidth())
        self.generalEmailSettings.setSizePolicy(sizePolicy)
        self.generalEmailSettings.setObjectName(_fromUtf8("generalEmailSettings"))
        self.gridLayout_4 = QtGui.QGridLayout(self.generalEmailSettings)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.hostnameIPTextbox = QtGui.QLineEdit(self.generalEmailSettings)
        self.hostnameIPTextbox.setObjectName(_fromUtf8("hostnameIPTextbox"))
        self.gridLayout_4.addWidget(self.hostnameIPTextbox, 0, 2, 1, 1)
        self.portLabel = QtGui.QLabel(self.generalEmailSettings)
        self.portLabel.setObjectName(_fromUtf8("portLabel"))
        self.gridLayout_4.addWidget(self.portLabel, 0, 3, 1, 1)
        self.portTextbox = QtGui.QLineEdit(self.generalEmailSettings)
        self.portTextbox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.portTextbox.setInputMask(_fromUtf8(""))
        self.portTextbox.setMaxLength(5)
        self.portTextbox.setObjectName(_fromUtf8("portTextbox"))
        self.gridLayout_4.addWidget(self.portTextbox, 0, 4, 1, 1)
        self.hostnameIPLabel = QtGui.QLabel(self.generalEmailSettings)
        self.hostnameIPLabel.setObjectName(_fromUtf8("hostnameIPLabel"))
        self.gridLayout_4.addWidget(self.hostnameIPLabel, 0, 0, 1, 2)
        self.usernameLabel = QtGui.QLabel(self.generalEmailSettings)
        self.usernameLabel.setObjectName(_fromUtf8("usernameLabel"))
        self.gridLayout_4.addWidget(self.usernameLabel, 1, 0, 1, 1)
        self.usernameTextbox = QtGui.QLineEdit(self.generalEmailSettings)
        self.usernameTextbox.setObjectName(_fromUtf8("usernameTextbox"))
        self.gridLayout_4.addWidget(self.usernameTextbox, 1, 2, 1, 1)
        self.passwordLabel = QtGui.QLabel(self.generalEmailSettings)
        self.passwordLabel.setObjectName(_fromUtf8("passwordLabel"))
        self.gridLayout_4.addWidget(self.passwordLabel, 2, 0, 1, 1)
        self.passwordTextbox = QtGui.QLineEdit(self.generalEmailSettings)
        self.passwordTextbox.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordTextbox.setObjectName(_fromUtf8("passwordTextbox"))
        self.gridLayout_4.addWidget(self.passwordTextbox, 2, 2, 1, 1)
        self.emailUseTLSCheck = QtGui.QCheckBox(self.generalEmailSettings)
        self.emailUseTLSCheck.setObjectName(_fromUtf8("emailUseTLSCheck"))
        self.gridLayout_4.addWidget(self.emailUseTLSCheck, 1, 4, 1, 1)
        self.mainGroupBoxLayout.addWidget(self.generalEmailSettings, 1, 0, 1, 1)
        self.mainDialogLayout.addWidget(self.mainFrame, 0, 0, 1, 4)
        
        self.guiFunctions = guiFunctions(self)
        
        self.retranslateUi(MainDialog)
        QtCore.QObject.connect(self.emailUseTLSCheck, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), self.guiFunctions.updateTLSState)
        QtCore.QObject.connect(self.StartButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.guiFunctions.startButton)
        QtCore.QObject.connect(self.QuitButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.guiFunctions.stopButton)
        QtCore.QObject.connect(self.StopButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainDialog.close)
        #Custom signals
        QtCore.QObject.connect(self.MW, QtCore.SIGNAL("sendEmail"), self.guiFunctions.sendEmail)
        QtCore.QObject.connect(self.MW, QtCore.SIGNAL("sendEmailFailed"), self.guiFunctions.sendEmailFailed)
        QtCore.QObject.connect(self.MW, QtCore.SIGNAL("firstRunOK"), self.guiFunctions.firstRunOK)
        QtCore.QObject.connect(self.MW, QtCore.SIGNAL("updateStatusBar"), self.guiFunctions.updateStatusBar)
        
        self.timer = QtCore.QTimer()
        QtCore.QObject.connect(self.timer, QtCore.SIGNAL("timeout()"), self.guiFunctions.watchForWindows)
        
        
        
        QtCore.QMetaObject.connectSlotsByName(MainDialog)
        MainDialog.setTabOrder(self.windowName, self.hostnameIPTextbox)
        MainDialog.setTabOrder(self.hostnameIPTextbox, self.portTextbox)
        MainDialog.setTabOrder(self.portTextbox, self.usernameTextbox)
        MainDialog.setTabOrder(self.usernameTextbox, self.passwordTextbox)
        MainDialog.setTabOrder(self.passwordTextbox, self.emailUseTLSCheck)
        MainDialog.setTabOrder(self.emailUseTLSCheck, self.emailFromTextbox)
        MainDialog.setTabOrder(self.emailFromTextbox, self.emailToTextbox)
        MainDialog.setTabOrder(self.emailToTextbox, self.emailSubjectTextbox)
        MainDialog.setTabOrder(self.emailSubjectTextbox, self.emailMessageTextbox)
        MainDialog.setTabOrder(self.emailMessageTextbox, self.StartButton)
        MainDialog.setTabOrder(self.StartButton, self.QuitButton)
        MainDialog.setTabOrder(self.QuitButton, self.StopButton)
        
        

    def retranslateUi(self, MainDialog):
        MainDialog.setWindowTitle(_translate("MainDialog", "WatchForWindow", None))
        self.curentStatusLabel.setText(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">Not watching for new windows...</span></p></body></html>", None))
        self.StartButton.setText(_translate("MainDialog", "Start", None))
        self.QuitButton.setText(_translate("MainDialog", "Stop", None))
        self.StopButton.setText(_translate("MainDialog", "Quit", None))
        self.windowOptionsGroup.setTitle(_translate("MainDialog", "Window Options", None))
        self.windowNameLabel.setText(_translate("MainDialog", "Window Name: ", None))
        self.emailMessageGroup.setTitle(_translate("MainDialog", "Enter Message", None))
        self.emailFromLabel.setText(_translate("MainDialog", "From:", None))
        self.emailFromTextbox.setToolTip(_translate("MainDialog", "Your email address.", None))
        self.emailToLabel.setText(_translate("MainDialog", "To:", None))
        self.emailToTextbox.setToolTip(_translate("MainDialog", "The recipient\'s email address.", None))
        self.emailSubjectLabel.setText(_translate("MainDialog", "Subject:", None))
        self.emailSubjectTextbox.setToolTip(_translate("MainDialog", "The subject of the email. You may use any of the shortcuts (listed on the left) here.", None))
        self.emailMessageLabel.setText(_translate("MainDialog", "Message:", None))
        self.emailMessageTextbox.setToolTip(_translate("MainDialog", "Your email address.", None))
        self.emailMessageTextbox.setText(_translate("MainDialog", "A new window has been opened named %name%", None))
        self.generalEmailSettings.setTitle(_translate("MainDialog", "E-Mail Server Options", None))
        self.hostnameIPTextbox.setToolTip(_translate("MainDialog", "The hostname or IP address of the outgoing SMTP server to use for sending emails.", None))
        self.portLabel.setText(_translate("MainDialog", "Port:", None))
        self.portTextbox.setToolTip(_translate("MainDialog", "The port number of the SMTP server (commonly 25, 465, or 587).", None))
        self.hostnameIPLabel.setText(_translate("MainDialog", "Hostname/IP:", None))
        self.usernameLabel.setText(_translate("MainDialog", "Username: ", None))
        self.usernameTextbox.setToolTip(_translate("MainDialog", "Username (if required) for the SMTP server.", None))
        self.passwordLabel.setText(_translate("MainDialog", "Password: ", None))
        self.passwordTextbox.setToolTip(_translate("MainDialog", "Password (if required) for the SMTP server.", None))
        self.emailUseTLSCheck.setToolTip(_translate("MainDialog", "This will enable/disable the use of TLS. It is highly recommended that you use TLS when possible.", None))
        self.emailUseTLSCheck.setText(_translate("MainDialog", "Use TLS", None))

